version: '3.8'

services:
  app:
    image: my-node-app:latest
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@my_db:5432/mydatabase
    command: ["/bin/sh", "-c", "npx prisma migrate deploy && npm run stage"]
    depends_on:
      my_db:
        condition: service_healthy

  my_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      retries: 5
      start_period: 10s
